<div id="contents">
		<div>
			<div class="body" id="about">
				<div id="sidebar">
					<div class="body">
                                           

						<img src="<?php echo $this->basePath('images/resort.png') ?>" alt="img"/>&nbsp;<?php echo $this->translate('') ?>
						<div class="contact">
							<p>
								For Order and Inquiries Please Call: <b>760-962-9541</b>
							</p>
						</div>
					</div>
				</div>
				<div id="main">
					<h1>About RFI</h1>

<h4>Our Mission</h4>
<p>To educate the South African public on how funeral insurance functions and to tailor design funeral policies that will cater for the needs of communities. 
RFI Life was organised to cater for the ever growing need for funeral insurance within South Africa from a company that would tailor design funeral policies to cater for community needs. </p>

<h4>Our Vision</h4>
<p>To be the best international Funeral Insurance company, catering to communities, companies, unions, church's and other industries with tailored made funeral policies that they can be proud of and identify with.</p>
 <iframe width="880" height="515" src="//www.youtube.com/embed/ASLYpMEBeYE" frameborder="0" allowfullscreen></iframe>
				</div>
                           
			</div>
		</div>
	</div>



