<div id="contents">
		<div>
			<div class="body" id="about">
			<div class="panel-body">
              
    <img src="<?php echo $this->basePath('images/funeral.jpg') ?>" alt="img" width="880px" height="380px"/>&nbsp;<?php echo $this->translate('') ?>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Insurance') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('<li>Compatative rates and cover</li>  <li>Repatriation anywhere in South Africa</li>  <li>No Medical Examination</li> <li>Airtime benefit</li> <li>Beef or Butchery benefit</li> <li>Payout between 6hrs - 24hrs</li> <li>Extended family members can be covered</li> <li>Over R300 000 worth of benefits (T&Cs apply)</li> <li>No waiting periods (T&Cs apply)</br><br/><p>Family Cover (14yrs-65yrs) Main member, spouse + up to 7 children</p></br><p>(inclusive benefits) Airtime & Repatriation.</p></li>
'), '<a href="">', '</a>', '<a href="">', '</a>', '<a href="">', '</a>') ?></p>
                
            </div>
        </div>
    </div>
     <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Optional benefit: Beef or grocery benefit R37.00 – cover of R6000') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('<table border="2" style="width:300px"><tr><td>COVER</td><td>RFI PREMIUM</td></tr><tr><td>R3000</td><td>R39.00</td></tr><tr><td>R4000</td><td>R49.00</td></tr><tr><td>R5000</td><td>R59.00</td></tr><tr><td>R6000</td><td>R66.00</td></tr><tr><td>R7000</td><td>R75.00</td></tr><tr><td>R8000</td><td>R82.00</td></tr><tr><td>R9000</td><td>R89.00</td></tr><tr><td>R10000</td><td>R99.00</td></tr></table><p>Single member Cover(14-65) Single Person + up to 7 children</p><p>(inclusive) Benefits; Airtime & Repatriation.</p>                                                                            
')) ?></p>
                
            </div>
        </div>
    </div>
     <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Optional benefit: Beef or grocery benefit R37.00 – cover of R6000') ?></h3>
            </div>
            <div class="panel-body">
            <p><?php echo sprintf($this->translate('<table border="2" style="width:300px"><tr><td>COVER</td><td>RFI PREMIUM</td></tr><tr><td>R3000</td><td>R32.00</td></tr><tr><td>R4000</td><td>R36.00</td></tr><tr><td>R5000</td><td>R42.00</td></tr><tr><td>R6000</td><td>R46.00</td></tr><tr><td>R7000</td><td>R52.00</td></tr><tr><td>R8000</td><td>R56.00</td></tr><tr><td>R9000</td><td>R62.00</td></tr><tr><td>R10000</td><td>R66.00</td></tr></table><p>Single member Cover(14-65) Single Person + up to 7 children</p><p>(inclusive) Benefits; Airtime & Repatriation.</p>                                                                            
')) ?></p>
                
            </div>
        </div>
    </div>
</div>
    

			</div>
		</div>
	</div>



